# https://github.com/release-drafter/release-drafter
---
name-template: '$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'

# Emoji reference: https://gitmoji.carloscuesta.me/
categories:
  - title: '🔒 Security Fixes'
    labels:
      - 'Type: Security'
  - title: '💥 Breaking Changes'
    labels:
      - 'Type: Breaking Change'
  - title: '🚀 Features'
    labels:
      - 'Type: Feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'Type: Bug'
  - title: '📝 Documentation'
    labels:
      - 'Type: Documentation'
  - title: '♻️ Refactoring'
    labels:
      - 'Type: Refactoring'
  - title: '✅ Testing'
    labels:
      - 'Type: Testing'
  - title: '🧰 Maintenance'
    labels:
      - 'Type: Maintenance'
  - title: '👷 CI'
    labels:
      - 'Type: CI'
  - title: '📦 Dependency Updates'
    labels:
      - 'Type: Dependencies'
    collapse-after: 5
  - title: '✍ Other changes'
exclude-labels:
  - 'skip-changelog'
  - 'Type: Meta'
  - 'Type: Question'
  - 'Type: Release'

template: |
  <!-- Optional: add a release summary here -->
  $CHANGES
